### ISSUE TITLE
US-11 : FR-11 - The system shall provide a field in the results that shows the source link for each academic article. 

### ISSUE THREAD

**Issue by beedawn** [beedawn/scrapescholar#29]
Priority:  9.5 High 
Estimation: 8 
Risk: Med-High
Title: US-11 
Requirement: R11

## User Story 
As a user, I want to be provided a link to the full text of the academic article, so that I can access the article.

### Acceptance Criteria 
Given a search has been conducted 
When user sees an article in the search results 
Then the link to the article’s source should be provided

## Subtasks 
- [x] Front end provides a link to the academic article through the UI (1 pt) (@assignee)
- [x] Backend provides link to article source to the front end via a GET request (7 pts) (@assignee)

#### Backend
- [x] when api returns results(results >0), article source link is provided
     - commit: [bb4512c](https://github.com/beedawn/scrapescholar/commit/bb4512c286ff62a16cdc95d07fef50bb069b9ad8)
- [x] when api results no results (results==0), no source link is provided
    - [bb4512c](https://github.com/beedawn/scrapescholar/commit/bb4512c286ff62a16cdc95d07fef50bb069b9ad8)
 - [x] test api environment variable are populated from .env file
     - [48827d5]

#### Front end
- [x] when results>0, article source link is displayed on page
    - [b47073e](https://github.com/beedawn/scrapescholar/commit/b47073e2542226cd7f8cab4ab1aeeb0b08da0f30)
- [x] when results==0, article source link is not displayed on page, and no results found message is displayed
    - [8f8ac1c](https://github.com/beedawn/scrapescholar/commit/8f8ac1c61f14f59e418c66b154f7f86fb1b936ec)

**Comment by beedawn** [comment]
tests:
backend
check that when api returns results(results >0), article source link is provided

front end
check that when results>0, article source link is displayed on page

**Comment by beedawn** [comment]
closed 9/13
