### ISSUE TITLE
Assignment 2 - Software Requirements

### ISSUE THREAD

**Issue by beedawn** [beedawn/scrapescholar#34]
Complete the course assignment.

Link:
https://pennstateoffice365.sharepoint.com/:w:/r/sites/Capstone894/_layouts/15/Doc2.aspx?action=edit&sourcedoc=%7B096b8aaf-ae2d-43d8-86fc-52e7bbe17142%7D&wdOrigin=TEAMS-MAGLEV.teamsSdk_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1725573476817&web=1

### Subtasks
- [x] Create Agile Board
- [ ] Compose user stories 15-25 Use Cases/User Stories for group projects
- [ ] Create initial backlog
- [ ] Non Functional Requirements
- [ ] Architecture Diagram
